# ===============================
# Server Configuration
# ===============================

server.port=8080


# ===============================
# Kafka Configuration
# ===============================

spring.kafka.bootstrap-servers=localhost:9092


# ===============================
# PostgreSQL Database Configuration
# ===============================

spring.datasource.url=jdbc:postgresql://localhost:5432/book_orders
spring.datasource.username=postgres
spring.datasource.password=eschew


# ===============================
# JPA / Hibernate Configuration
# ===============================

# Automatically creates/updates tables based on @Entity classes
spring.jpa.hibernate.ddl-auto=update

# Show SQL queries in console (useful for development)
spring.jpa.show-sql=true

# PostgreSQL dialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect